export const NavItemType = {
  DASHBOARD: "DASHBOARD",
  DEPARTMENT: "DEPARTMENT",
  ATTENDANCE: "ATTENDANCE",
  CONSULTATION: "CONSULTATION",
  MYPAGE: "MYPAGE",
  POINT_MALL: "POINT_MALL",

  // 관리자 전용 내비게이션
  ADMIN_USERS: "ADMIN_USERS",
  ADMIN_MONITORING: "ADMIN_MONITORING",
  ADMIN_APPLICATIONS: "ADMIN_APPLICATIONS",
};

export const UserRole = {
  STAFF: "STAFF",
  ADMIN: "ADMIN",
};
